/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef PROJET_PRIVATE_H
#define PROJET_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.0.197"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	0
#define VER_BUILD	197
#define COMPANY_NAME	"LECRUBIER OLIVIER"
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"Supanoid"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"1.0"

#endif /*PROJET_PRIVATE_H*/
